"""
Builds a Luau bundle of a Rojo project tree so the standalone Luau CLI can
mount it into the Roblox mock (tools/mock/Roblox.luau).

Supports the Rojo subset used by this repository: "$path" to a file or a
directory, "$className", and explicit children. File classes follow Rojo:
  *.server.luau -> Script, *.client.luau -> LocalScript, *.luau -> ModuleScript,
  a directory with init.luau -> ModuleScript, otherwise Folder.

Usage: python3 tools/bundle.py <project.json> <out.luau> [--node Name ...]
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def long_string(text):
    level = 1
    while ("]" + "=" * level + "]") in text:
        level += 1
    eq = "=" * level
    return "[" + eq + "[\n" + text + "]" + eq + "]"

def file_node(path, name=None):
    base = os.path.basename(path)
    for suffix, cls in ((".server.luau", "Script"), (".client.luau", "LocalScript"), (".luau", "ModuleScript")):
        if base.endswith(suffix):
            return {"Name": name or base[: -len(suffix)], "ClassName": cls, "Source": open(path).read(), "Path": os.path.relpath(path, ROOT), "Children": []}
    return None

def dir_node(path, name=None):
    init = os.path.join(path, "init.luau")
    if os.path.exists(init):
        node = file_node(init, name or os.path.basename(path))
    else:
        node = {"Name": name or os.path.basename(path), "ClassName": "Folder", "Children": []}
    for entry in sorted(os.listdir(path)):
        full = os.path.join(path, entry)
        if entry.startswith(".") or entry == "init.luau":
            continue
        child = dir_node(full) if os.path.isdir(full) else file_node(full)
        if child:
            node["Children"].append(child)
    return node

def project_node(name, spec, base):
    node = None
    if "$path" in spec:
        path = os.path.join(base, spec["$path"])
        node = dir_node(path, name) if os.path.isdir(path) else file_node(path, name)
    if node is None:
        node = {"Name": name, "ClassName": spec.get("$className", "Folder"), "Children": []}
    for key, child in spec.items():
        if key.startswith("$"):
            continue
        node["Children"].append(project_node(key, child, base))
    return node

def emit(node, indent=0):
    pad = "\t" * indent
    parts = [pad + "{", f'{pad}\tName = "{node["Name"]}",', f'{pad}\tClassName = "{node["ClassName"]}",']
    if "Source" in node:
        parts.append(f'{pad}\tPath = "{node["Path"]}",')
        parts.append(f"{pad}\tSource = {long_string(node['Source'])},")
    parts.append(pad + "\tChildren = {")
    for child in node["Children"]:
        parts.append(emit(child, indent + 2) + ",")
    parts.append(pad + "\t},")
    parts.append(pad + "}")
    return "\n".join(parts)

def main():
    project_path, out_path = sys.argv[1], sys.argv[2]
    project = json.load(open(project_path))
    base = os.path.dirname(os.path.abspath(project_path))
    tree = project_node(project["name"], project["tree"], base)
    with open(out_path, "w") as f:
        f.write("-- Generated by tools/bundle.py. Do not edit.\nreturn " + emit(tree) + "\n")

if __name__ == "__main__":
    main()
