"""
Generates Documentation/CONFIG_SCHEMA.md and Documentation/PRESETS.md from the
machine-readable schemas (run tools/gen_docs.sh first; it calls this script).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA_DIR = os.path.join(ROOT, "Documentation", "schema")

full = json.load(open(os.path.join(SCHEMA_DIR, "visualfx.schema.json")))
presets = json.load(open(os.path.join(SCHEMA_DIR, "presets.json")))


def fmt_default(value):
    if value is None:
        return ""
    if isinstance(value, dict) and "$type" in value:
        t = value["$type"]
        if t == "Color3":
            return "rgb(%s)" % ", ".join(str(round(c)) for c in value["rgb"])
        if t == "Vector3":
            return "(%s)" % ", ".join(str(c) for c in value["xyz"])
        if t == "NumberRange":
            return "%s..%s" % (value["min"], value["max"])
        return t
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def kind_text(field):
    kind = field["Kind"]
    if kind == "EnumItem":
        return "Enum.%s" % field.get("Enum")
    if kind == "string" and field.get("Values"):
        return "string: " + " \\| ".join(field["Values"])
    return kind


def range_text(field):
    parts = []
    if field.get("Min") is not None or field.get("Max") is not None:
        parts.append("%s – %s" % (field.get("Min", "−∞"), field.get("Max", "∞")))
    if field.get("SoftMax") is not None:
        parts.append("recommended ≤ %s" % field["SoftMax"])
    return "; ".join(parts)


def field_rows(fields, prefix=""):
    rows = []
    nested = []
    for field in fields:
        key = prefix + field["Key"]
        if field["Kind"] == "object":
            nested.append((key, field.get("Fields", []), field.get("Description")))
            rows.append("| `%s` | object | | | see below | %s |" % (key, field.get("Description") or ""))
            continue
        if field["Kind"] == "map":
            nested.append((key + ".<name>", field.get("ItemFields", []), field.get("Description")))
            rows.append("| `%s` | map of objects | | | see below | %s |" % (key, field.get("Description") or ""))
            continue
        aliases = ", ".join("`%s`" % a for a in field.get("Aliases") or [])
        desc = field.get("Description") or ""
        if field.get("Required"):
            desc = "**Required.** " + desc
        if aliases:
            desc += " Aliases: %s." % aliases
        prop = field.get("Property") or ""
        rows.append("| `%s` | %s | %s | %s | %s | %s |" % (
            key, kind_text(field), range_text(field), fmt_default(field.get("Default")),
            ("`%s`" % prop) if prop else "", desc.strip()))
    return rows, nested


def table(fields, prefix=""):
    header = ["| Key | Type | Range | Default | Roblox property | Notes |", "| --- | --- | --- | --- | --- | --- |"]
    rows, nested = field_rows(fields, prefix)
    out = header + rows
    for key, child_fields, description in nested:
        out.append("")
        out.append("**`%s`**%s" % (key, (" — " + description) if description else ""))
        out.append("")
        out.extend(table(child_fields))
    return out


lines = []
lines.append("# VisualFX Configuration Schema (version %d)" % full["ConfigVersion"])
lines.append("")
lines.append("> Generated by `tools/gen_docs.sh` from the live registries. Machine-readable forms:")
lines.append("> `schema/config.schema.json` (JSON Schema draft-07), `schema/visualfx.schema.json` (full VisualFX schema")
lines.append("> including weather types, particle templates, director vocabulary and commands), `schema/presets.json`.")
lines.append("")
lines.append("""A configuration is a plain table. Every key is optional; only sections that
are present are managed. Unknown keys produce warnings (with suggestions) and
are ignored.

```lua
{
    Version = 1,
    Metadata = { Name = "Cinematic Sunset", Author = "VisualFX", Description = "...", Category = "Cinematic", Tags = { "sunset" } },
    Inherits = { "Sunset" },            -- optional preset composition
    Quality = { Level = "High" },
    Lighting = {...}, Atmosphere = {...}, Sky = {...}, Clouds = {...},
    PostProcessing = { Bloom = {...}, ColorCorrection = {...}, DepthOfField = {...}, SunRays = {...}, Blur = {...} },
    Water = {...},
    Particles = { [name] = {...} },
    Weather = { Type = "HeavyRain", Intensity = 0.8, ... },
    Environment = { Wind = {...}, DayNight = {...}, Zones = { [name] = {...} } },
    Effects = { [id] = { Effect = "<registered effect>", ... } },
}
```

## Properties of the format

* **Deterministic.** Exports sort keys (priority keys such as `Version`, `Metadata`, `Type` first) and print numbers with the shortest round-tripping form. The same configuration always produces byte-identical JSON, so exports are diffable.
* **Serializable.** Roblox values use tagged JSON encodings (below); `ImportConfiguration` accepts tables, `VisualFXConfig` documents and JSON text.
* **Versioned.** `Version` is the schema version. A configuration without `Version` is treated as version 0 and migrated.
* **Validated.** Every configuration is validated before use (types, ranges, enums, required fields, references, compatibility, conflicts, performance).
* **Composable.** `Inherits` merges presets left to right before the configuration's own values.

## Merge rules

Used by `UpdateScene`, `Set*` setters, preset inheritance and transitions:
""")
for rule in full["MergeRules"]:
    lines.append("1. " + rule)
lines.append("")
lines.append("""## Value encodings

In Luau you pass Roblox values directly. JSON (and AI agents) can use either
the tagged form or a shorthand; both are validated and converted.

| Kind | Tagged JSON | Shorthands |
| --- | --- | --- |""")
for kind, enc in full["ValueEncodings"].items():
    lines.append("| %s | `%s` | %s |" % (kind, json.dumps(enc["Tagged"], separators=(",", ":")), ", ".join("`%s`" % s for s in enc["Shorthand"])))
lines.append("")
lines.append("Enum items may also be given by name (`\"Box\"`, case-insensitive) or by value number. "
             "Enum item lists in the JSON Schema reflect the generator's engine model; the running engine is always authoritative.")
lines.append("")
lines.append("""## Schema migration

| From | To | Changes |
| --- | --- | --- |
| 0 (unversioned) | 1 | `Lighting.PostProcessing` → `PostProcessing`; `Particles` array → dictionary keyed by `Name`; `Weather = "Type"` → `{ Type = "Type" }`; `Water.WaterColor`/`WaterTransparency`/... → `Water.Color`/`Transparency`/... |

Newer versions than the runtime supports are rejected with a clear error.
""")
for section in full["Sections"]:
    lines.append("## %s" % section["Name"])
    lines.append("")
    if section.get("Description"):
        lines.append(section["Description"])
        lines.append("")
    if section["Kind"] == "object":
        lines.extend(table(section["Fields"]))
    else:
        lines.append("Dictionary keyed by name (letters, digits, spaces, `_`, `-`). Each entry:")
        lines.append("")
        lines.extend(table(section["ItemFields"]))
    lines.append("")
    if section["Name"] == "Weather":
        lines.append("### Weather types")
        lines.append("")
        lines.append("| Type | Category | Defaults | Composed of | Description |")
        lines.append("| --- | --- | --- | --- | --- |")
        for name, w in sorted(full["WeatherTypes"].items()):
            defaults = ", ".join("%s=%s" % (k, fmt_default(v)) for k, v in sorted(w["Defaults"].items()))
            lines.append("| `%s` | %s | %s | %s | %s |" % (name, w.get("Category", ""), defaults, ", ".join(w["Composition"]), w.get("Description", "")))
        lines.append("")
        lines.append("""Weather blends the scene's own values (or Roblox defaults when a section is
not configured) toward the weather's targets by `Intensity`. `Fog` adds
Atmosphere density/haze (and ground mist at ≥ 0.45). `Wind` sets
`Workspace.GlobalWind` unless `Environment.Wind` is configured, and pushes
rain/snow sideways. Component intensities (`RainIntensity`, …) override
`Intensity` for that component. Weather-owned instances are replaced, never
accumulated, when the weather changes.
""")
    if section["Name"] == "Particles":
        lines.append("### Particle templates")
        lines.append("")
        lines.append("| Template | Description |")
        lines.append("| --- | --- |")
        for name, t in sorted(full["ParticleTemplates"].items()):
            lines.append("| `%s` | %s |" % (name, t.get("Description", "")))
        lines.append("")
        lines.append("""A system's `Template` defaults to its name when that matches a template,
otherwise `Custom`. Configured values override template defaults. `Rate` is
scaled by the quality profile and budgets (see PERFORMANCE.md).
""")

with open(os.path.join(ROOT, "Documentation", "CONFIG_SCHEMA.md"), "w") as f:
    f.write("\n".join(lines) + "\n")

# PRESETS.md
p = []
p.append("# VisualFX Presets")
p.append("")
p.append("> Generated by `tools/gen_docs.sh`. Resolved configurations for every preset: `schema/presets.json`.")
p.append("")
p.append("""Presets are plain configuration data stored as ModuleScripts in
`Presets/BuiltIn` (read-only) and `Presets/User`, or saved at runtime with
`VisualFX:SavePreset` (persisted through a storage adapter; the Studio plugin
uses `plugin:SetSetting`).

```lua
VisualFX:ApplyPreset("CinematicSunset")                        -- replace the managed scene
VisualFX:ApplyPreset("LightRain", { Merge = true })            -- merge into the current scene
VisualFX:ApplyPreset("Night", { Transition = { Duration = 6 } })
VisualFX:ApplyPreset("Storm", { Overrides = { Weather = { Intensity = 1 } } })
VisualFX:SavePreset("MyEnvironment", VisualFX:ExportConfiguration())
VisualFX:DeletePreset("MyEnvironment")
```

## Composition

`Inherits` lists presets merged **left to right**, then the preset's own
values are merged last (dictionaries merge recursively, scalars/arrays
replace, `"$remove"` deletes). `Metadata` is never inherited. Missing parents
and cycles are validation errors.

```text
BaseForest + Autumn + LightRain = AutumnRainForest
```

```lua
return {
    Version = 1,
    Metadata = { Name = "Autumn Rain Forest", Category = "Forest" },
    Inherits = { "BaseForest", "Autumn", "LightRain" },
    Weather = { Intensity = 0.55 },
}
```

Compose on the fly with `VisualFX:ComposePresets({ "BaseForest", "Autumn", "LightRain" }, overrides)`.

## Built-in presets
""")
p.append("| Preset | Category | Inherits | Sections | Description |")
p.append("| --- | --- | --- | --- | --- |")
for name, entry in sorted(presets.items()):
    s = entry["Summary"]
    resolved = entry["Resolved"]
    sections = [k for k in resolved.keys() if k not in ("Version", "Metadata", "Inherits")]
    p.append("| `%s` | %s | %s | %s | %s |" % (name, s["Category"], ", ".join(s.get("Inherits") or []), ", ".join(sections), s["Description"]))
p.append("")
p.append("""## Writing a preset

```lua
-- Presets/User/MistyForest.luau (or save with VisualFX:SavePreset)
return {
    Version = 1,
    Metadata = { Name = "Misty Forest", Category = "Forest" },
    Atmosphere = {
        Density = 0.45,
        Haze = 2.5,
        Glare = 0,
        Color = Color3.fromRGB(170, 190, 175),
        Decay = Color3.fromRGB(90, 110, 100),
    },
    Lighting = { ClockTime = 8, Brightness = 1.5, ExposureCompensation = 0 },
    Weather = { Type = "Fog", Intensity = 0.6 },
}
```

Presets are validated when applied or saved, so a broken preset never
partially applies.
""")
with open(os.path.join(ROOT, "Documentation", "PRESETS.md"), "w") as f:
    f.write("\n".join(p) + "\n")
print("markdown written")
